# Generated by Django 6.0.4 on 2026-04-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SWOTAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField(help_text='The startup idea or concept being analyzed')),
                ('strength', models.JSONField(default=list, help_text='List of strengths')),
                ('weakness', models.JSONField(default=list, help_text='List of weaknesses')),
                ('opportunity', models.JSONField(default=list, help_text='List of opportunities')),
                ('threat', models.JSONField(default=list, help_text='List of threats')),
                ('market_data', models.JSONField(blank=True, help_text='Market research data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SWOT Analysis',
                'verbose_name_plural': 'SWOT Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
