# Generated by Django 6.0.4 on 2026-05-06 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='swotanalysis',
            name='feasibility_report',
            field=models.JSONField(blank=True, help_text='Feasibility analysis data', null=True),
        ),
        migrations.AddField(
            model_name='swotanalysis',
            name='is_detailed',
            field=models.BooleanField(default=False, help_text='Detailed report flag'),
        ),
        migrations.AddField(
            model_name='swotanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swot_analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.IntegerField(default=0, help_text='Number of SWOT analyses used')),
                ('is_premium', models.BooleanField(default=False, help_text='Premium subscription status')),
                ('premium_start_date', models.DateTimeField(blank=True, help_text='Premium start date', null=True)),
                ('premium_expiry_date', models.DateTimeField(blank=True, help_text='Premium expiry date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
